### PR TITLE
Updated config file from version 1.0.3 to 1.0.4

### PR DESCRIPTION
**Pull request by PolarisAstrum**
Updated config file from version 1.0.3 to 1.0.4 using latest annotation files.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep_CEN_config/5)

### CODE REVIEW

**Review by sophie22 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep_CEN_config/5)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @PolarisAstrum)

___
*[`cen_vep_config_v1.0.4.json` line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep_CEN_config/5#-NQynoUO59vYDTjrC71M:-NQynoUO59vYDTjrC71N:b-ift8yo) ([raw file](https://github.com/eastgenomics/eggd_vep_CEN_config/blob/03eec15c7cfd0e00722fc9c61ed3bfc5aad1860a/cen_vep_config_v1.0.4.json#L5)):*
> ```JSON
>         "genome_build": "GRCh37",
>         "assay":"CEN",
>         "config_version": "1.0.3"
> ```

please also update the version within the config
___
*[`cen_vep_config_v1.0.4.json` line 26 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep_CEN_config/5#-NQynsyjDNLRW2tAxocp:-NQynsyjDNLRW2tAxocq:bsat5g2) ([raw file](https://github.com/eastgenomics/eggd_vep_CEN_config/blob/03eec15c7cfd0e00722fc9c61ed3bfc5aad1860a/cen_vep_config_v1.0.4.json#L26)):*
> ```JSON
>         "resource_files": [
>           {
>           "file_id":"file-GQ9X2z844610JY75Yk6Jg1qz",
> ```

could you access this file? For me DNAnexus errors that file could not be located

**Comment by PolarisAstrum** [comment]
I used the file IDs from https://cuhbioinformatics.atlassian.net/wiki/spaces/O/pages/2884861967/230315+update+ClinVar+annotation+source+March
Is this correct?

**Comment by PolarisAstrum** [comment]
How do I search DNAnexus for those specific files to check if they exist?

**Review by sophie22 — COMMENTED** [review]
approved versions should be taken from this folder: https://platform.dnanexus.com/panx/projects/Fkb6Gkj433GVVvj73J7x8KbV/data/annotation/b37/clinvar
and more generally from the 001_Reference project in DNAnexus

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep_CEN_config/5#-:-NQytEax-kMRCN1V8A8_:bk68jyq)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @PolarisAstrum)

**Comment by mattgarner** [comment]
Obsolete - closing

**Pull request closed without merging**
